name: sample-workflow

# Change the 'on:' values to determine when your workflow will run
on:
  issue_comment:
    types: [created]

# These are the minimum permissions required to run the workflow and comment on both PRs and Issues
permissions:
  issues: write
  pull-requests: write

jobs:
  sample:
    # if: github.event_name == 'pull_request' && github.event.action == 'opened' # only run on new PRs or Issues
    runs-on: ubuntu-latest
    steps:
      # It is required to checkout the repo if using the 'file:' param to read a file for template rendering
      - uses: actions/checkout@v4

      # Add a comment to the issue or PR
      - uses: GrantBirki/comment@vX.X.X
        with:
          file: demo/render-sample.md
          vars: |
            sha: ${{ github.sha }}
            environment: production
            app: cool-app
