name: acceptance

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  acceptance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # if on pull request
      - uses: ./
        if: github.event_name == 'pull_request'
        with:
            file: demo/acceptance.md
            vars: |
              sha: ${{ github.sha }}
              environment: production
              app: cool-app
