name: lint
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # pin@v5

      - name: setup node
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # pin@v5
        with:
          node-version-file: .node-version
          cache: 'npm'

      - name: install dependencies
        run: npm ci

      - name: lint
        run: |
          npm run format-check
          npm run lint
