name: sample-workflow

on:
  issue_comment:
    types: [created]

permissions:
  issues: write
  pull-requests: write

jobs:
  sample:
    # if: github.event_name == 'pull_request' && github.event.action == 'opened' # only run on new PRs or Issues
    runs-on: ubuntu-latest
    steps:
      # Need to checkout for testing the Action in this repo
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # pin@v3.0.2

      # Add a comment to the issue or PR
      - uses: ./
        with:
          file: demo/render-sample.md
          vars: |
            sha: ${{ github.sha }}
            environment: production
            app: cool-app
